baseURL = "https://tothemoon.uy"
languageCode = "en-us"
title = "To The Moon"
theme = "tothemoon2"

[params.meta]
	title = "To The Moon Studio"
	description = "We create stories and identities" #max 200 characters
	url = "tothemoon.uy"
	image = "/img/p1.png" #JPG, PNG, WEBP and GIF. SVG not supporter. Max 5MB.
	twitterUser = "@tothemoonuy" # @user


